import type { SharedGameConfig } from '@/domains/hyper-swiper/shared/game-config.types'

export const SERVER_GAME_CONFIG: SharedGameConfig & {
  COIN_TTL_MS: number
  MAX_ACTIVE_COINS: number
  COIN_SPAWN_INTERVALS_MS: number[]
  CLIENT_READY_TIMEOUT_MS: number
  STALE_PLAYER_TIMEOUT_MS: number
  ROOM_DELETION_DELAY_MS: number
  CLEANUP_INTERVAL_MS: number
  PRICE_BROADCAST_THROTTLE_MS: number
  PRICE_RECONNECT_DELAY_MS: number
  PRICE_RESET_INTERVAL_MS: number
  DEFAULT_SCENE_WIDTH: number
  DEFAULT_SCENE_HEIGHT: number
} = {
  STARTING_BALANCE: 100,
  POSITION_COLLATERAL: 10,
  FIXED_LEVERAGE: 500,
  MAX_POSITIONS: 10,
  LIQUIDATION_THRESHOLD: 0.8,

  COIN_TTL_MS: 5000,
  MAX_ACTIVE_COINS: 4,
  COIN_SPAWN_INTERVALS_MS: [1200, 1200, 1200, 1200, 1200],

  CLIENT_READY_TIMEOUT_MS: 10000,
  STALE_PLAYER_TIMEOUT_MS: 30000,
  ROOM_DELETION_DELAY_MS: 1000,
  CLEANUP_INTERVAL_MS: 30000,

  PRICE_BROADCAST_THROTTLE_MS: 100,
  PRICE_RECONNECT_DELAY_MS: 5000,
  PRICE_RESET_INTERVAL_MS: 60000,

  DEFAULT_SCENE_WIDTH: 500,
  DEFAULT_SCENE_HEIGHT: 800,
} as const
