/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GridRouteImport } from './routes/grid'
import { Route as HyperSwiperRouteImport } from './routes/hyper-swiper'
import { Route as StockArcadeRouteImport } from './routes/stock-arcade'
import { Route as TapDancerRouteImport } from './routes/tap-dancer'
import { Route as TestRouteImport } from './routes/test'
import { Route as DotwellKnownFarcasterDotjsonRouteImport } from './routes/[.]well-known.farcaster[.]json'
import { Route as ApiAuthRouteImport } from './routes/api.auth'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiWebhookRouteImport } from './routes/api.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GridRoute = GridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const HyperSwiperRoute = HyperSwiperRouteImport.update({
  id: '/hyper-swiper',
  path: '/hyper-swiper',
  getParentRoute: () => rootRouteImport,
} as any)
const StockArcadeRoute = StockArcadeRouteImport.update({
  id: '/stock-arcade',
  path: '/stock-arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const TapDancerRoute = TapDancerRouteImport.update({
  id: '/tap-dancer',
  path: '/tap-dancer',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownFarcasterDotjsonRoute =
  DotwellKnownFarcasterDotjsonRouteImport.update({
    id: '/.well-known/farcaster.json',
    path: '/.well-known/farcaster.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookRoute = ApiWebhookRouteImport.update({
  id: '/api/webhook',
  path: '/api/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grid': typeof GridRoute
  '/hyper-swiper': typeof HyperSwiperRoute
  '/stock-arcade': typeof StockArcadeRoute
  '/tap-dancer': typeof TapDancerRoute
  '/test': typeof TestRoute
  '/.well-known/farcaster.json': typeof DotwellKnownFarcasterDotjsonRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/health': typeof ApiHealthRoute
  '/api/webhook': typeof ApiWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grid': typeof GridRoute
  '/hyper-swiper': typeof HyperSwiperRoute
  '/stock-arcade': typeof StockArcadeRoute
  '/tap-dancer': typeof TapDancerRoute
  '/test': typeof TestRoute
  '/.well-known/farcaster.json': typeof DotwellKnownFarcasterDotjsonRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/health': typeof ApiHealthRoute
  '/api/webhook': typeof ApiWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grid': typeof GridRoute
  '/hyper-swiper': typeof HyperSwiperRoute
  '/stock-arcade': typeof StockArcadeRoute
  '/tap-dancer': typeof TapDancerRoute
  '/test': typeof TestRoute
  '/.well-known/farcaster.json': typeof DotwellKnownFarcasterDotjsonRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/health': typeof ApiHealthRoute
  '/api/webhook': typeof ApiWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/grid'
    | '/hyper-swiper'
    | '/stock-arcade'
    | '/tap-dancer'
    | '/test'
    | '/.well-known/farcaster.json'
    | '/api/auth'
    | '/api/health'
    | '/api/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/grid'
    | '/hyper-swiper'
    | '/stock-arcade'
    | '/tap-dancer'
    | '/test'
    | '/.well-known/farcaster.json'
    | '/api/auth'
    | '/api/health'
    | '/api/webhook'
  id:
    | '__root__'
    | '/'
    | '/grid'
    | '/hyper-swiper'
    | '/stock-arcade'
    | '/tap-dancer'
    | '/test'
    | '/.well-known/farcaster.json'
    | '/api/auth'
    | '/api/health'
    | '/api/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GridRoute: typeof GridRoute
  HyperSwiperRoute: typeof HyperSwiperRoute
  StockArcadeRoute: typeof StockArcadeRoute
  TapDancerRoute: typeof TapDancerRoute
  TestRoute: typeof TestRoute
  DotwellKnownFarcasterDotjsonRoute: typeof DotwellKnownFarcasterDotjsonRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiWebhookRoute: typeof ApiWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid': {
      id: '/grid'
      path: '/grid'
      fullPath: '/grid'
      preLoaderRoute: typeof GridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hyper-swiper': {
      id: '/hyper-swiper'
      path: '/hyper-swiper'
      fullPath: '/hyper-swiper'
      preLoaderRoute: typeof HyperSwiperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-arcade': {
      id: '/stock-arcade'
      path: '/stock-arcade'
      fullPath: '/stock-arcade'
      preLoaderRoute: typeof StockArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tap-dancer': {
      id: '/tap-dancer'
      path: '/tap-dancer'
      fullPath: '/tap-dancer'
      preLoaderRoute: typeof TapDancerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/farcaster.json': {
      id: '/.well-known/farcaster.json'
      path: '/.well-known/farcaster.json'
      fullPath: '/.well-known/farcaster.json'
      preLoaderRoute: typeof DotwellKnownFarcasterDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook': {
      id: '/api/webhook'
      path: '/api/webhook'
      fullPath: '/api/webhook'
      preLoaderRoute: typeof ApiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GridRoute: GridRoute,
  HyperSwiperRoute: HyperSwiperRoute,
  StockArcadeRoute: StockArcadeRoute,
  TapDancerRoute: TapDancerRoute,
  TestRoute: TestRoute,
  DotwellKnownFarcasterDotjsonRoute: DotwellKnownFarcasterDotjsonRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiWebhookRoute: ApiWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
